// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: lib/lib.proto

package lib

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_lib_lib_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_lib_lib_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_lib_lib_proto_rawDescGZIP(), []int{0}
}

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_lib_lib_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_lib_lib_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_lib_lib_proto_rawDescGZIP(), []int{1}
}

func (x *Id) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           int32                  `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_lib_lib_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_lib_lib_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_lib_lib_proto_rawDescGZIP(), []int{2}
}

func (x *Value) GetVal() int32 {
	if x != nil {
		return x.Val
	}
	return 0
}

type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Length        int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_lib_lib_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_lib_lib_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_lib_lib_proto_rawDescGZIP(), []int{3}
}

func (x *Register) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Register) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type Write struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Val           int32                  `protobuf:"varint,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Write) Reset() {
	*x = Write{}
	mi := &file_lib_lib_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Write) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Write) ProtoMessage() {}

func (x *Write) ProtoReflect() protoreflect.Message {
	mi := &file_lib_lib_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Write.ProtoReflect.Descriptor instead.
func (*Write) Descriptor() ([]byte, []int) {
	return file_lib_lib_proto_rawDescGZIP(), []int{4}
}

func (x *Write) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Write) GetVal() int32 {
	if x != nil {
		return x.Val
	}
	return 0
}

type ChanList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chans         []*Id                  `protobuf:"bytes,1,rep,name=chans,proto3" json:"chans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChanList) Reset() {
	*x = ChanList{}
	mi := &file_lib_lib_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChanList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChanList) ProtoMessage() {}

func (x *ChanList) ProtoReflect() protoreflect.Message {
	mi := &file_lib_lib_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChanList.ProtoReflect.Descriptor instead.
func (*ChanList) Descriptor() ([]byte, []int) {
	return file_lib_lib_proto_rawDescGZIP(), []int{5}
}

func (x *ChanList) GetChans() []*Id {
	if x != nil {
		return x.Chans
	}
	return nil
}

var File_lib_lib_proto protoreflect.FileDescriptor

const file_lib_lib_proto_rawDesc = "" +
	"\n" +
	"\rlib/lib.proto\x12\x03lib\"\x06\n" +
	"\x04Void\"\x14\n" +
	"\x02Id\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x05Value\x12\x10\n" +
	"\x03val\x18\x01 \x01(\x05R\x03val\"2\n" +
	"\bRegister\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\")\n" +
	"\x05Write\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03val\x18\x02 \x01(\x05R\x03val\")\n" +
	"\bChanList\x12\x1d\n" +
	"\x05chans\x18\x01 \x03(\v2\a.lib.IdR\x05chans2\x8a\x01\n" +
	"\x05Chans\x12\"\n" +
	"\x04List\x12\t.lib.Void\x1a\r.lib.ChanList\"\x00\x12!\n" +
	"\x03Reg\x12\r.lib.Register\x1a\t.lib.Void\"\x00\x12\x1d\n" +
	"\x02Wr\x12\n" +
	".lib.Write\x1a\t.lib.Void\"\x00\x12\x1b\n" +
	"\x02Rd\x12\a.lib.Id\x1a\n" +
	".lib.Value\"\x00B\x06Z\x04/libb\x06proto3"

var (
	file_lib_lib_proto_rawDescOnce sync.Once
	file_lib_lib_proto_rawDescData []byte
)

func file_lib_lib_proto_rawDescGZIP() []byte {
	file_lib_lib_proto_rawDescOnce.Do(func() {
		file_lib_lib_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lib_lib_proto_rawDesc), len(file_lib_lib_proto_rawDesc)))
	})
	return file_lib_lib_proto_rawDescData
}

var file_lib_lib_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_lib_lib_proto_goTypes = []any{
	(*Void)(nil),     // 0: lib.Void
	(*Id)(nil),       // 1: lib.Id
	(*Value)(nil),    // 2: lib.Value
	(*Register)(nil), // 3: lib.Register
	(*Write)(nil),    // 4: lib.Write
	(*ChanList)(nil), // 5: lib.ChanList
}
var file_lib_lib_proto_depIdxs = []int32{
	1, // 0: lib.ChanList.chans:type_name -> lib.Id
	0, // 1: lib.Chans.List:input_type -> lib.Void
	3, // 2: lib.Chans.Reg:input_type -> lib.Register
	4, // 3: lib.Chans.Wr:input_type -> lib.Write
	1, // 4: lib.Chans.Rd:input_type -> lib.Id
	5, // 5: lib.Chans.List:output_type -> lib.ChanList
	0, // 6: lib.Chans.Reg:output_type -> lib.Void
	0, // 7: lib.Chans.Wr:output_type -> lib.Void
	2, // 8: lib.Chans.Rd:output_type -> lib.Value
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lib_lib_proto_init() }
func file_lib_lib_proto_init() {
	if File_lib_lib_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lib_lib_proto_rawDesc), len(file_lib_lib_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lib_lib_proto_goTypes,
		DependencyIndexes: file_lib_lib_proto_depIdxs,
		MessageInfos:      file_lib_lib_proto_msgTypes,
	}.Build()
	File_lib_lib_proto = out.File
	file_lib_lib_proto_goTypes = nil
	file_lib_lib_proto_depIdxs = nil
}
