//
//Copyright 2018-2026
//Unai Martinez-Corral <unai.martinezcorral@ehu.eus>
//University of the Basque Country (UPV/EHU) <ehu.eus>
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: lib/lib.proto

package lib

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_lib_lib_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_lib_lib_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_lib_lib_proto_rawDescGZIP(), []int{0}
}

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_lib_lib_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_lib_lib_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_lib_lib_proto_rawDescGZIP(), []int{1}
}

func (x *Id) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Adr           int32                  `protobuf:"varint,1,opt,name=adr,proto3" json:"adr,omitempty"`
	Dat           int32                  `protobuf:"varint,2,opt,name=dat,proto3" json:"dat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_lib_lib_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_lib_lib_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_lib_lib_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetAdr() int32 {
	if x != nil {
		return x.Adr
	}
	return 0
}

func (x *Message) GetDat() int32 {
	if x != nil {
		return x.Dat
	}
	return 0
}

type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Length        int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_lib_lib_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_lib_lib_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_lib_lib_proto_rawDescGZIP(), []int{3}
}

func (x *Register) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Register) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type Write struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg           *Message               `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Write) Reset() {
	*x = Write{}
	mi := &file_lib_lib_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Write) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Write) ProtoMessage() {}

func (x *Write) ProtoReflect() protoreflect.Message {
	mi := &file_lib_lib_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Write.ProtoReflect.Descriptor instead.
func (*Write) Descriptor() ([]byte, []int) {
	return file_lib_lib_proto_rawDescGZIP(), []int{4}
}

func (x *Write) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Write) GetMsg() *Message {
	if x != nil {
		return x.Msg
	}
	return nil
}

type ChanList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []*Id                  `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChanList) Reset() {
	*x = ChanList{}
	mi := &file_lib_lib_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChanList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChanList) ProtoMessage() {}

func (x *ChanList) ProtoReflect() protoreflect.Message {
	mi := &file_lib_lib_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChanList.ProtoReflect.Descriptor instead.
func (*ChanList) Descriptor() ([]byte, []int) {
	return file_lib_lib_proto_rawDescGZIP(), []int{5}
}

func (x *ChanList) GetIds() []*Id {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_lib_lib_proto protoreflect.FileDescriptor

const file_lib_lib_proto_rawDesc = "" +
	"\n" +
	"\rlib/lib.proto\x12\x03lib\"\x06\n" +
	"\x04Void\"\x14\n" +
	"\x02Id\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\aMessage\x12\x10\n" +
	"\x03adr\x18\x01 \x01(\x05R\x03adr\x12\x10\n" +
	"\x03dat\x18\x02 \x01(\x05R\x03dat\"2\n" +
	"\bRegister\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\"7\n" +
	"\x05Write\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\x03msg\x18\x02 \x01(\v2\f.lib.MessageR\x03msg\"%\n" +
	"\bChanList\x12\x19\n" +
	"\x03ids\x18\x01 \x03(\v2\a.lib.IdR\x03ids2\x8c\x01\n" +
	"\x05Chans\x12\"\n" +
	"\x04List\x12\t.lib.Void\x1a\r.lib.ChanList\"\x00\x12!\n" +
	"\x03Reg\x12\r.lib.Register\x1a\t.lib.Void\"\x00\x12\x1d\n" +
	"\x02Wr\x12\n" +
	".lib.Write\x1a\t.lib.Void\"\x00\x12\x1d\n" +
	"\x02Rd\x12\a.lib.Id\x1a\f.lib.Message\"\x00B\x06Z\x04/libb\x06proto3"

var (
	file_lib_lib_proto_rawDescOnce sync.Once
	file_lib_lib_proto_rawDescData []byte
)

func file_lib_lib_proto_rawDescGZIP() []byte {
	file_lib_lib_proto_rawDescOnce.Do(func() {
		file_lib_lib_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lib_lib_proto_rawDesc), len(file_lib_lib_proto_rawDesc)))
	})
	return file_lib_lib_proto_rawDescData
}

var file_lib_lib_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_lib_lib_proto_goTypes = []any{
	(*Void)(nil),     // 0: lib.Void
	(*Id)(nil),       // 1: lib.Id
	(*Message)(nil),  // 2: lib.Message
	(*Register)(nil), // 3: lib.Register
	(*Write)(nil),    // 4: lib.Write
	(*ChanList)(nil), // 5: lib.ChanList
}
var file_lib_lib_proto_depIdxs = []int32{
	2, // 0: lib.Write.msg:type_name -> lib.Message
	1, // 1: lib.ChanList.ids:type_name -> lib.Id
	0, // 2: lib.Chans.List:input_type -> lib.Void
	3, // 3: lib.Chans.Reg:input_type -> lib.Register
	4, // 4: lib.Chans.Wr:input_type -> lib.Write
	1, // 5: lib.Chans.Rd:input_type -> lib.Id
	5, // 6: lib.Chans.List:output_type -> lib.ChanList
	0, // 7: lib.Chans.Reg:output_type -> lib.Void
	0, // 8: lib.Chans.Wr:output_type -> lib.Void
	2, // 9: lib.Chans.Rd:output_type -> lib.Message
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_lib_lib_proto_init() }
func file_lib_lib_proto_init() {
	if File_lib_lib_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lib_lib_proto_rawDesc), len(file_lib_lib_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lib_lib_proto_goTypes,
		DependencyIndexes: file_lib_lib_proto_depIdxs,
		MessageInfos:      file_lib_lib_proto_msgTypes,
	}.Build()
	File_lib_lib_proto = out.File
	file_lib_lib_proto_goTypes = nil
	file_lib_lib_proto_depIdxs = nil
}
