// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: lib/lib.proto

package lib

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Chans_List_FullMethodName = "/lib.Chans/List"
	Chans_Reg_FullMethodName  = "/lib.Chans/Reg"
	Chans_Wr_FullMethodName   = "/lib.Chans/Wr"
	Chans_Rd_FullMethodName   = "/lib.Chans/Rd"
)

// ChansClient is the client API for Chans service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChansClient interface {
	List(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ChanList, error)
	Reg(ctx context.Context, in *Register, opts ...grpc.CallOption) (*Void, error)
	Wr(ctx context.Context, in *Write, opts ...grpc.CallOption) (*Void, error)
	Rd(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Value, error)
}

type chansClient struct {
	cc grpc.ClientConnInterface
}

func NewChansClient(cc grpc.ClientConnInterface) ChansClient {
	return &chansClient{cc}
}

func (c *chansClient) List(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ChanList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChanList)
	err := c.cc.Invoke(ctx, Chans_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chansClient) Reg(ctx context.Context, in *Register, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, Chans_Reg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chansClient) Wr(ctx context.Context, in *Write, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, Chans_Wr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chansClient) Rd(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Value, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Value)
	err := c.cc.Invoke(ctx, Chans_Rd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChansServer is the server API for Chans service.
// All implementations should embed UnimplementedChansServer
// for forward compatibility.
type ChansServer interface {
	List(context.Context, *Void) (*ChanList, error)
	Reg(context.Context, *Register) (*Void, error)
	Wr(context.Context, *Write) (*Void, error)
	Rd(context.Context, *Id) (*Value, error)
}

// UnimplementedChansServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChansServer struct{}

func (UnimplementedChansServer) List(context.Context, *Void) (*ChanList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedChansServer) Reg(context.Context, *Register) (*Void, error) {
	return nil, status.Error(codes.Unimplemented, "method Reg not implemented")
}
func (UnimplementedChansServer) Wr(context.Context, *Write) (*Void, error) {
	return nil, status.Error(codes.Unimplemented, "method Wr not implemented")
}
func (UnimplementedChansServer) Rd(context.Context, *Id) (*Value, error) {
	return nil, status.Error(codes.Unimplemented, "method Rd not implemented")
}
func (UnimplementedChansServer) testEmbeddedByValue() {}

// UnsafeChansServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChansServer will
// result in compilation errors.
type UnsafeChansServer interface {
	mustEmbedUnimplementedChansServer()
}

func RegisterChansServer(s grpc.ServiceRegistrar, srv ChansServer) {
	// If the following call panics, it indicates UnimplementedChansServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chans_ServiceDesc, srv)
}

func _Chans_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChansServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chans_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChansServer).List(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chans_Reg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Register)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChansServer).Reg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chans_Reg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChansServer).Reg(ctx, req.(*Register))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chans_Wr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Write)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChansServer).Wr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chans_Wr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChansServer).Wr(ctx, req.(*Write))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chans_Rd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChansServer).Rd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chans_Rd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChansServer).Rd(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

// Chans_ServiceDesc is the grpc.ServiceDesc for Chans service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chans_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lib.Chans",
	HandlerType: (*ChansServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Chans_List_Handler,
		},
		{
			MethodName: "Reg",
			Handler:    _Chans_Reg_Handler,
		},
		{
			MethodName: "Wr",
			Handler:    _Chans_Wr_Handler,
		},
		{
			MethodName: "Rd",
			Handler:    _Chans_Rd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lib/lib.proto",
}
